// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc2oy5z14hS-EgO0IBOuz7oII52ShL3_U',
    appId: '1:334370226709:web:d177e6d3619450bd4b841c',
    messagingSenderId: '334370226709',
    projectId: 'foodhub-8f40d',
    authDomain: 'foodhub-8f40d.firebaseapp.com',
    databaseURL: 'https://foodhub-8f40d-default-rtdb.firebaseio.com',
    storageBucket: 'foodhub-8f40d.firebasestorage.app',
    measurementId: 'G-CJW8B0SXNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBRJ72Y79PBPwgbGmJNtpLBuouv6PtFAU',
    appId: '1:334370226709:android:db7ba07b2f104f014b841c',
    messagingSenderId: '334370226709',
    projectId: 'foodhub-8f40d',
    databaseURL: 'https://foodhub-8f40d-default-rtdb.firebaseio.com',
    storageBucket: 'foodhub-8f40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewGF98PH2nBBN91AONPQmkUq5gKZmLVg',
    appId: '1:334370226709:ios:00502ca41baca6a14b841c',
    messagingSenderId: '334370226709',
    projectId: 'foodhub-8f40d',
    databaseURL: 'https://foodhub-8f40d-default-rtdb.firebaseio.com',
    storageBucket: 'foodhub-8f40d.firebasestorage.app',
    iosBundleId: 'com.example.foodHubAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewGF98PH2nBBN91AONPQmkUq5gKZmLVg',
    appId: '1:334370226709:ios:00502ca41baca6a14b841c',
    messagingSenderId: '334370226709',
    projectId: 'foodhub-8f40d',
    databaseURL: 'https://foodhub-8f40d-default-rtdb.firebaseio.com',
    storageBucket: 'foodhub-8f40d.firebasestorage.app',
    iosBundleId: 'com.example.foodHubAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc2oy5z14hS-EgO0IBOuz7oII52ShL3_U',
    appId: '1:334370226709:web:e030a32af2f2bc384b841c',
    messagingSenderId: '334370226709',
    projectId: 'foodhub-8f40d',
    authDomain: 'foodhub-8f40d.firebaseapp.com',
    databaseURL: 'https://foodhub-8f40d-default-rtdb.firebaseio.com',
    storageBucket: 'foodhub-8f40d.firebasestorage.app',
    measurementId: 'G-M2JMB97KPC',
  );
}
